#org.tbk.tor.auto-publish-enabled=false

org:
  tbk:
    tor:
      auto-publish-enabled: false
      startup-timeout: 120s
      #enabled: false

app:
  downloader:
    model:
      ulozto: https://github.com/JanPalasek/ulozto-captcha-breaker/releases/download/v2.2/model.zip

logging:
  level:
    org.berndpruenster.netlayer.tor: debug